travis:
  secure:
    BINSTAR_TOKEN: f56T1nHOSTZYcSGGnYfKLmDA9v2Drt/r7WmIzcDjqr5GWIgujQMkP23EmrNy1lG8PyisufDZ50j3Drs9tDBJgDPRZbdoM0j8iq+kX0qVO2uMLCqKGo5CsWPwbNSKaSsZzWvsfxA6XU/GQSgxmxnf7FdskhE15OLPUsjt8CDj7tLlIArEPJ+12sQZPL/loI/7DthCvRsKgQmNLP7z6reXq4PUp2/70VIEpg7+NjPb3LC2TZ2XttHJTj5szUszAmqowGaRfZEI1bZWYC8XKKrHQFQEvXq7rDY5ZZeqOxq1QZWw+sd6a6P/xReKDlLXrQDYGVp5AkipLJRsRnWUt+jMS654EkW6JVdUpfSkXWZzO0Wwweh7bk67x1je3zL9TkEtBV/vV8r2DSdMuXE4oSS3p3LlcG3VnpR/Q/haQgeH2R6FGiJjP9jTSy0U+aBQ1o26mF3lqNNnDWODSA87iGynsD8+P9xX1dvHnE0p+jjM+TqcVvE9KGo2URVPqlMDcqQCiq8X+Ds5Cp69FnvsHg/xUnRPZKC2r4GA+ApcotHPvTN+5VSi85vdsypQy6Bw+loTE2Xls/Jv3Ei8709UG5SqMmknfywOk5epKT/DRb3MOAmU1D+QK02rTj1yzxKUFUnIvBDyZrOiTiDmFbB8BpXlwWt7P7gTBNHOPgLZzg5crps=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
